issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - errcheck
    - unused
  enable:
    - errorlint
    - gocritic
    - gofumpt
    - goimports
    - govet
    - revive
    - staticcheck

linters-settings:
  goimports:
    local-prefixes: github.com/prometheus/promu
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: true
